# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b95b3a53119904725ab6e0a932ede25a0ecc331a0207e9cd7f149c68b1d9965ab08c71dbd20cb4d56a7a1d60ec01b33b2baf18241db38196507a443b41d8a9b

test:
  secret_key_base: 284cd82fe266d0f389d7a7da5d832a0b8bce7787cc2c0609b4d523c0aeade573c71a4ed86748693cb59906766d67a109c022f9a60332eeeaede46dc2fad3cbb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
